### ISSUE TITLE
Explicit treatment of symbolic links

### ISSUE THREAD

**Issue by vks** [jessegrosjean/jwalk#7]
Currently, jwalk use `std::fs::metadata`. However, sometimes `std::fs::symlink_metadata` is preferable. Also, sometimes it is preferable not to follow symbolic links.

As far I can see, it is not documented how symbolic links are treated.

**Comment by jessegrosjean** [comment]
Yes, I haven't added any support for how symbolic links are handled.

I think this could probably be added by adding new options and then implementing the options here:

https://docs.rs/jwalk/0.4.0/src/jwalk/lib.rs.html#136

I skipped this because I didn't need it, but would accept a pull request that adds. I would follow walker's implementation where possible. Checking for loops in symbolic links might be harder then single threaded implementation. Maybe see what ignore crate implementation does if that's a problem.

**Comment by vks** [comment]
> I skipped this because I didn't need it, but would accept a pull request that adds.

It would be useful for [dua](https://github.com/Byron/dua-cli) to give more accurate sizes of directories.

**Comment by vks** [comment]
See #9, which adds documentation for the current behavior.

**Comment by jessegrosjean** [comment]
jwalk now handles symlinks like walkdir.
